### ISSUE TITLE
API integration

### ISSUE THREAD

**Issue by s0rau** [caronc/newsreap#6]
:bulb: **The Idea**
I really like to CLI idea, it's very fast ;)
Do you plan to add the Newznab API (https://inhies.github.io/Newznab-API/functions/) in order to call newsreap API with other software ?

**Comment by caronc** [comment]
I honestly haven't touched this code in a while. I don't see creating an API for it anytime on the horizon, but if you want to leverage it and build upon it yourself, i'd be excited to see what you put together!
